language: python
python:
- "2.7"
- "3.6"

node_js:
- 7

cache: pip

before_install:
# Upgrade pip setuptools and wheel
- pip install --upgrade pip

install:
- pip install -e .[pre-commit]

script:
- sed -i 's/show/save/i' example.py; python example.py


jobs:
  include:
    - stage: deploy
      # Make sure the tag is valid semver
      if: "tag =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+(a|b|rc)?[0-9]*$"
      services: ignore
      addons: skip
      python: 3.6
      before_install: skip
      install: skip
      before_script: skip
      script: skip
      env: ignore
      before_deploy:
        - echo "About to deploy $TRAVIS_TAG to PyPI"
      after_deploy:
        - echo "Deployed $TRAVIS_TAG to PyPI"
      deploy: &pypi
        provider: pypi
        skip_existing: true
        username: aiida-bot
        password:
          # See https://docs.travis-ci.com/user/encryption-keys/ for instructions
          secure: "nwKs9GjMkbZv0fqHYmox/QyHZG05WNTaHDUA17LOrqSYWVEi48ZnzMeRQ9bVU2WO17I//0SPyM4E8UvagLtkGSoaJ/YGclIJP2Zmvtm7l8ghS5Owgabh5K9soY44bZ0hyz1SiY8Y9QMS2pQxSLI4h3hRfvFT5vFh5Jj/rnuZsbCkR2VKEwfCbxopht7BtDDpeJJHAk5NSXJmlHoOPVXSRmI44tDMl0qmGSq8RAgRwWF8rEOkYJK6GSWmYVTF+qiu+kPT7v/jqcfHoDYLCWhLxbQxrG3LTq8BhhmfUVTmwpDPv9oiOnNajb5bNyMyWXLjA2bH/PlXiPJSjNiA5SwI7Y88rS1XH0QIxMsJB91ZgxcpVaWC1PkilV+ed5adkVzFc/eH14/hRfTULh/vlVjveMYqS+nyDfGQS9re2MX0Ck1rXfNw5MmcRxqRLdUlkl4chv4YcsI+xm3OQBcRqVca+vQ4A85wMtaVKATbh6tc3wzVPg6NCyapmRF3iyIqyPMld3fnbtS4kEjNlqYcAROt1VInOcu9SSZs3GT61q57Ty5bBjftBW2kIXWMzgFFikFNkJHsRoEs39e+n5NV/SX/pPo98l5DGy10I2aw42uDvcOgx5na+wc6s20E7VPGm3Y3BPJuNZz54s7hXM5wrJunVE3l+himIV2AAgAQzNdxhVg="
        on:
          repo: ltalirz/jsmol-bokeh-extension
          branch: master
          tags: true
